[package]
name = "five-in-a-row"
version = "0.1.0"
authors = ["Oskari Lehto <oskari.lehto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6"
rayon = "1.1"
# tensorflow = "0.14.0"
